data:
  name: Burgers
  datapath: '../data/lwr.mat'
  total_num: 100
  offset: 0
  n_sample: 1
  nx: 64
  nt: 29
  sub: 1
  sub_t: 1

model:
  layers: [16, 24, 24, 32, 32]
  modes1: [15, 12, 9, 9]
  modes2: [15, 12, 9, 9]
  fc_dim: 64
  act: gelu
  num_pad: 4

train:
  batchsize: 20
  epochs: 200
  milestones: [150, 300, 450]
  base_lr: 0.001
  scheduler_gamma: 0.5
  ic_loss: 500.0
  f_loss:  1000.0
  xy_loss: 0.0
  save_dir: 'lwr-FDM'
  save_name: 'lwr-pretrain-eqn.pt'

log:
  project: PINO-lwr-pretrain
  group: gelu-eqn
  entity: hzzheng-pino

