data:
  name: Burgers
  datapath_rho: '../data/non-sep-rhos.mat'
  datapath_V: '../data/non-sep-Vs.mat'
  total_num: 10 # change
  offset: 0 # change
  n_sample: 4 # change
  nx: 8
  nt: 7
  sub: 1
  sub_t: 1

model:
  layers: [16, 24, 24, 32, 32]
  modes1: [5, 5, 5, 5]
  modes2: [5, 5, 5, 5]
  fc_dim: 64
  act: gelu
  num_pad: 4

train:
  batchsize: 4 # change
  epochs: 50
  milestones: [150, 300, 450]
  base_lr: 0.005
  scheduler_gamma: 0.5
  ic_loss: 5
  f_loss: 10
  xy_loss: 0
  step_rho: 50
  step_V: 50
  save_dir_rho: 'nonsep-couple-rho'
  save_name_rho: 'nonsep-couple-rho.pt'
  save_dir_V: 'nonsep-couple-V'
  save_name_V: 'nonsep-couple-V.pt'

log:
  project: PINO-lwr-pretrain
  group: gelu-eqn
  entity: hzzheng-pino

